### ISSUE TITLE
Optioneel

### ISSUE THREAD

**Issue by DwarfExop** [DwarfExop/domotica#8]
Optioneel/Bonus voor de A-opdracht (of alvast ideeën voor B-opdracht). Toepassen van meer sensoren (bijv. luchtdruk, luchtvochtigheid, infrarood, afstand, aanraak)

- 1. Configuratie van de sensoren via de app (bijv. koppeling aan IO-pin, bereik, spanning)
- 2. Grafische weergave van data, met grafiekjes en trends.
- 3. Dynamische grenzen i.p.v. statische grenzen (snelle stijging per tijdseenheid).
- 4. Logging of eenvoudige dataopslag van sensorgegevens.
- 5. Koppeling van tijdfuncties aan Google agenda (lamp aan: 27 jan. 9.00 uur en uit 27 jan. om 14.00 uur

**Comment by jildertvenema** [comment]
@dlpXdrone12 @Meurth 

Jullie kunnen puntje 2 en 4 wel doen, ik zou beginnen met 4. Je kan hiervoor gewoon de spanning als invoer gebruiken van een willekeurige pin, dan kunnen we dat later vervangen door een sensor.

xoxo Lars
