### ISSUE TITLE
Verbinden met Xamarin-app

### ISSUE THREAD

**Issue by DwarfExop** [DwarfExop/domotica#9]
Thema's nog te bespreken

### Voorbeelden:
> 1. een modern en app-configureerbaar inbraakalarm
> 2. een geautomatiseerde koffiezetter met personifiëring en agendakoppeling
> 3. een weerstation met geautomatiseerde acties (regenscherm neer bij regen) en lokale weervoorspelling
> 4. een geavanceerde indoor lichtregeling met sfeerdetectie
> 5. een bediening voor binnenhuis audio en video met smart afstandsbediening en Kodi-integratie
> 6. een systeem voor indoor klimaatcontrole (van huiskamer, schuur of kas) met thermostaatkoppeling
> 7. een systeem voor huisbeveiliging met integratie van bijvoorbeeld glasbreuk- en
> 8. rooksensoren.

**Comment by jildertvenema** [comment]
We basically did the connection..

**Comment by DwarfExop** [comment]
Het idee luid:

Je komt de kamer binnen, als het donker is gaat het licht aan. De gordijnen gaan dicht zodra het donker word en open wanneer het licht is. Je kan de tv aanzetten via de app.
